version: '3.8'
services:

  # MongoDB Service
  mongo:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongo-data:/data/db

  # Mongo Express (for easy database visualization)
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpassword
      - ME_CONFIG_MONGODB_URL=mongodb://admin:adminpassword@mongo:27017/

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://admin:adminpassword@mongo:27017
    depends_on:
      - mongo

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"

  # Admin Service
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin_container
    ports:
      - "5174:5174"

volumes:
  mongo-data:
